// Deterministic Awalé (Oware Abapa) rule engine — TypeScript port.
//
// This is a line-for-line mirror of contracts/src/AwaleRules.sol. The off-chain
// game server runs this engine; the on-chain ReplayVerifier runs the Solidity
// one. Determinism is load-bearing: given the same start state and ordered
// moves, both must reach byte-identical state, so a fraud proof always agrees
// with what the server computed. The parity test (test/parity.test.ts) replays
// vectors generated by the Solidity engine and asserts that match.
//
// Board layout (sowing runs counter-clockwise, index increasing):
//
//     North (player 1)   11  10   9   8   7   6
//                        --  --  --  --  --  --
//     South (player 0)     0   1   2   3   4   5
//
// pits[0..5] belong to player 0 (South); pits[6..11] to player 1 (North).

export const PITS = 12;
export const HOUSES_PER_SIDE = 6;
export const SEEDS = 48;
/** Winner sentinel for a draw (0 and 1 are the two players). */
export const DRAW = 2;

export interface GameState {
  /** 0..5 = player 0 (South), 6..11 = player 1 (North). */
  pits: number[];
  store0: number;
  store1: number;
  /** 0 or 1 — player to move. */
  turn: number;
  over: boolean;
  /** Valid only when `over`: 0, 1, or DRAW. */
  winner: number;
}

/** The standard opening position: 4 seeds in every house, player 0 to move. */
export function initialState(): GameState {
  return { pits: Array(PITS).fill(4), store0: 0, store1: 0, turn: 0, over: false, winner: 0 };
}

function rowSum(pits: number[], player: number): number {
  const base = player === 0 ? 0 : HOUSES_PER_SIDE;
  let total = 0;
  for (let h = 0; h < HOUSES_PER_SIDE; h++) total += pits[base + h];
  return total;
}

/** Sow all seeds from house `idx` counter-clockwise, skipping the origin. */
function sow(pits: number[], idx: number): { pits: number[]; lastPos: number } {
  const out = pits.slice();
  let seeds = out[idx];
  out[idx] = 0;
  let pos = idx;
  while (seeds > 0) {
    pos = (pos + 1) % PITS;
    if (pos === idx) continue; // never drop back into the origin house
    out[pos] += 1;
    seeds -= 1;
  }
  return { pits: out, lastPos: pos };
}

/** Resolve captures for `turn`, honouring the grand-slam rule. */
function capture(pits: number[], turn: number, lastPos: number): { pits: number[]; captured: number } {
  const out = pits.slice();
  const [lo, hi] = turn === 0 ? [6, 11] : [0, 5];

  if (lastPos < lo || lastPos > hi) return { pits: out, captured: 0 };

  let p = lastPos;
  let take = 0;
  while (p >= lo && (out[p] === 2 || out[p] === 3)) {
    take += out[p];
    p -= 1;
  }
  if (take === 0) return { pits: out, captured: 0 };

  let oppTotal = 0;
  for (let k = lo; k <= hi; k++) oppTotal += out[k];
  if (take === oppTotal) return { pits: out, captured: 0 }; // grand slam: capture nothing

  p = lastPos;
  while (p >= lo && (out[p] === 2 || out[p] === 3)) {
    out[p] = 0;
    p -= 1;
  }
  return { pits: out, captured: take };
}

/** Bitmask (bits 0..5) of the houses the current player may legally play. */
export function legalMovesMask(s: GameState): number {
  if (s.over) return 0;
  const oppEmpty = rowSum(s.pits, 1 - s.turn) === 0;
  const base = s.turn === 0 ? 0 : HOUSES_PER_SIDE;
  let mask = 0;
  for (let h = 0; h < HOUSES_PER_SIDE; h++) {
    const idx = base + h;
    if (s.pits[idx] === 0) continue;
    if (oppEmpty) {
      const { pits: np } = sow(s.pits, idx);
      if (rowSum(np, 1 - s.turn) === 0) continue;
    }
    mask |= 1 << h;
  }
  return mask;
}

/** Whether playing `house` (0..5) is legal in state `s`. */
export function isLegal(s: GameState, house: number): boolean {
  if (house >= HOUSES_PER_SIDE) return false;
  return (legalMovesMask(s) & (1 << house)) !== 0;
}

function finish(s: GameState): void {
  s.over = true;
  if (s.store0 > s.store1) s.winner = 0;
  else if (s.store1 > s.store0) s.winner = 1;
  else s.winner = DRAW;
}

function zeroBoard(s: GameState): void {
  for (let i = 0; i < PITS; i++) s.pits[i] = 0;
}

/** Determine and stamp terminal conditions on a freshly-advanced state. */
function resolve(s: GameState): void {
  if (s.store0 > SEEDS / 2) return finish(s);
  if (s.store1 > SEEDS / 2) return finish(s);

  const ownSum = rowSum(s.pits, s.turn);
  if (ownSum === 0) {
    const oppSum = rowSum(s.pits, 1 - s.turn);
    if (s.turn === 0) s.store1 += oppSum;
    else s.store0 += oppSum;
    zeroBoard(s);
    return finish(s);
  }

  const opp = rowSum(s.pits, 1 - s.turn);
  if (opp === 0 && legalMovesMask(s) === 0) {
    if (s.turn === 0) s.store0 += ownSum;
    else s.store1 += ownSum;
    zeroBoard(s);
    finish(s);
  }
}

/**
 * Apply one move and return the resulting state. Throws on any illegal move,
 * mirroring the Solidity `require`s so both engines reject the same transcripts.
 * @param house house index 0..5 relative to the current player
 */
export function applyMove(s: GameState, house: number): GameState {
  if (s.over) throw new Error("AwaleRules: game over");
  if (house >= HOUSES_PER_SIDE) throw new Error("AwaleRules: bad house");

  const idx = s.turn === 0 ? house : HOUSES_PER_SIDE + house;
  if (s.pits[idx] === 0) throw new Error("AwaleRules: empty house");

  const oppEmpty = rowSum(s.pits, 1 - s.turn) === 0;
  const { pits: sown, lastPos } = sow(s.pits, idx);

  if (oppEmpty && rowSum(sown, 1 - s.turn) === 0) {
    throw new Error("AwaleRules: must feed opponent");
  }

  const { pits: board, captured } = capture(sown, s.turn, lastPos);

  const r: GameState = {
    pits: board,
    store0: s.store0,
    store1: s.store1,
    turn: 1 - s.turn,
    over: false,
    winner: 0,
  };
  if (s.turn === 0) r.store0 += captured;
  else r.store1 += captured;

  resolve(r);
  return r;
}
