// Deterministic Awalé (Oware Abapa) rule engine — TypeScript port.
//
// This is a line-for-line mirror of contracts/src/AwaleRules.sol. The off-chain
// game server runs this engine; the on-chain ReplayVerifier runs the Solidity
// one. Determinism is load-bearing: given the same start state and ordered
// moves, both must reach byte-identical state, so a fraud proof always agrees
// with what the server computed. The parity test (test/parity.test.ts) replays
// vectors generated by the Solidity engine and asserts that match.
//
// Board layout (sowing runs counter-clockwise, index increasing):
//
//     North (player 1)   11  10   9   8   7   6
//                        --  --  --  --  --  --
//     South (player 0)     0   1   2   3   4   5
//
// pits[0..5] belong to player 0 (South); pits[6..11] to player 1 (North).

export const PITS = 12;
export const HOUSES_PER_SIDE = 6;
export const SEEDS = 48;
/** Winner sentinel for a draw (0 and 1 are the two players). */
export const DRAW = 2;

/** Consecutive non-capturing plies after which the game is split — the ultimate
 *  backstop against endless cyclic positions (see `resolve`). Repetition
 *  detection (see `adjudicate`) normally ends a cycle far sooner. */
export const NO_CAPTURE_LIMIT = 40;

/** How many times a position (board + player to move) may recur SINCE THE LAST
 *  CAPTURE before the game is declared a provable cycle and ended. Threefold,
 *  as in chess: the players had two chances to deviate and didn't. */
export const REPETITION_LIMIT = 3;

export interface GameState {
  /** 0..5 = player 0 (South), 6..11 = player 1 (North). */
  pits: number[];
  store0: number;
  store1: number;
  /** 0 or 1 — player to move. */
  turn: number;
  over: boolean;
  /** Valid only when `over`: 0, 1, or DRAW. */
  winner: number;
  /** Plies since the last capture; reset to 0 on any capture. */
  noCaptureCount: number;
}

/** The standard opening position: 4 seeds in every house, player 0 to move. */
export function initialState(): GameState {
  return { pits: Array(PITS).fill(4), store0: 0, store1: 0, turn: 0, over: false, winner: 0, noCaptureCount: 0 };
}

function rowSum(pits: number[], player: number): number {
  const base = player === 0 ? 0 : HOUSES_PER_SIDE;
  let total = 0;
  for (let h = 0; h < HOUSES_PER_SIDE; h++) total += pits[base + h];
  return total;
}

/** Sow all seeds from house `idx` counter-clockwise, skipping the origin. */
function sow(pits: number[], idx: number): { pits: number[]; lastPos: number } {
  const out = pits.slice();
  let seeds = out[idx];
  out[idx] = 0;
  let pos = idx;
  while (seeds > 0) {
    pos = (pos + 1) % PITS;
    if (pos === idx) continue; // never drop back into the origin house
    out[pos] += 1;
    seeds -= 1;
  }
  return { pits: out, lastPos: pos };
}

/** Resolve captures for `turn`, honouring the grand-slam rule. */
function capture(pits: number[], turn: number, lastPos: number): { pits: number[]; captured: number } {
  const out = pits.slice();
  const [lo, hi] = turn === 0 ? [6, 11] : [0, 5];

  if (lastPos < lo || lastPos > hi) return { pits: out, captured: 0 };

  let p = lastPos;
  let take = 0;
  while (p >= lo && (out[p] === 2 || out[p] === 3)) {
    take += out[p];
    p -= 1;
  }
  if (take === 0) return { pits: out, captured: 0 };

  let oppTotal = 0;
  for (let k = lo; k <= hi; k++) oppTotal += out[k];
  if (take === oppTotal) return { pits: out, captured: 0 }; // grand slam: capture nothing

  p = lastPos;
  while (p >= lo && (out[p] === 2 || out[p] === 3)) {
    out[p] = 0;
    p -= 1;
  }
  return { pits: out, captured: take };
}

/** Bitmask (bits 0..5) of the houses the current player may legally play. */
export function legalMovesMask(s: GameState): number {
  if (s.over) return 0;
  const oppEmpty = rowSum(s.pits, 1 - s.turn) === 0;
  const base = s.turn === 0 ? 0 : HOUSES_PER_SIDE;
  let mask = 0;
  for (let h = 0; h < HOUSES_PER_SIDE; h++) {
    const idx = base + h;
    if (s.pits[idx] === 0) continue;
    if (oppEmpty) {
      const { pits: np } = sow(s.pits, idx);
      if (rowSum(np, 1 - s.turn) === 0) continue;
    }
    mask |= 1 << h;
  }
  return mask;
}

/** Whether playing `house` (0..5) is legal in state `s`. */
export function isLegal(s: GameState, house: number): boolean {
  if (house >= HOUSES_PER_SIDE) return false;
  return (legalMovesMask(s) & (1 << house)) !== 0;
}

function finish(s: GameState): void {
  s.over = true;
  if (s.store0 > s.store1) s.winner = 0;
  else if (s.store1 > s.store0) s.winner = 1;
  else s.winner = DRAW;
}

function zeroBoard(s: GameState): void {
  for (let i = 0; i < PITS; i++) s.pits[i] = 0;
}

/** Determine and stamp terminal conditions on a freshly-advanced state. */
function resolve(s: GameState): void {
  if (s.store0 > SEEDS / 2) return finish(s);
  if (s.store1 > SEEDS / 2) return finish(s);

  const ownSum = rowSum(s.pits, s.turn);
  if (ownSum === 0) {
    const oppSum = rowSum(s.pits, 1 - s.turn);
    if (s.turn === 0) s.store1 += oppSum;
    else s.store0 += oppSum;
    zeroBoard(s);
    return finish(s);
  }

  const opp = rowSum(s.pits, 1 - s.turn);
  if (opp === 0 && legalMovesMask(s) === 0) {
    if (s.turn === 0) s.store0 += ownSum;
    else s.store1 += ownSum;
    zeroBoard(s);
    return finish(s);
  }

  // Endless cyclic position guard: neither side has captured in a long time,
  // so no legal sequence is going anywhere — split the board and end in a draw
  // (or a lead-preserving win) rather than let the game run forever.
  if (s.noCaptureCount >= NO_CAPTURE_LIMIT) {
    s.store0 += rowSum(s.pits, 0);
    s.store1 += rowSum(s.pits, 1);
    zeroBoard(s);
    finish(s);
  }
}

/**
 * Apply one move and return the resulting state. Throws on any illegal move,
 * mirroring the Solidity `require`s so both engines reject the same transcripts.
 * @param house house index 0..5 relative to the current player
 */
export function applyMove(s: GameState, house: number): GameState {
  if (s.over) throw new Error("AwaleRules: game over");
  if (house >= HOUSES_PER_SIDE) throw new Error("AwaleRules: bad house");

  const idx = s.turn === 0 ? house : HOUSES_PER_SIDE + house;
  if (s.pits[idx] === 0) throw new Error("AwaleRules: empty house");

  const oppEmpty = rowSum(s.pits, 1 - s.turn) === 0;
  const { pits: sown, lastPos } = sow(s.pits, idx);

  if (oppEmpty && rowSum(sown, 1 - s.turn) === 0) {
    throw new Error("AwaleRules: must feed opponent");
  }

  const { pits: board, captured } = capture(sown, s.turn, lastPos);

  const r: GameState = {
    pits: board,
    store0: s.store0,
    store1: s.store1,
    turn: 1 - s.turn,
    over: false,
    winner: 0,
    noCaptureCount: captured > 0 ? 0 : s.noCaptureCount + 1,
  };
  if (s.turn === 0) r.store0 += captured;
  else r.store1 += captured;

  resolve(r);
  return r;
}

/** Canonical key of a position: the board plus whose turn it is. Two moments
 *  with the same key are the same position — the whole game continues the same
 *  way from both, so if one recurs the game is going in circles. */
export function positionKey(s: GameState): string {
  return `${s.pits.join(",")}|${s.turn}`;
}

/** End a provably-cyclic game the official Awalé way: each side collects the
 *  seeds in its own row, then the seed leader wins (equal ⇒ draw). Identical
 *  award to the NO_CAPTURE_LIMIT split — only the trigger is earlier. */
function endByCycle(s: GameState): GameState {
  const store0 = s.store0 + rowSum(s.pits, 0);
  const store1 = s.store1 + rowSum(s.pits, 1);
  return {
    pits: Array(PITS).fill(0),
    store0,
    store1,
    turn: s.turn,
    over: true,
    winner: store0 > store1 ? 0 : store1 > store0 ? 1 : DRAW,
    noCaptureCount: s.noCaptureCount,
  };
}

/**
 * Authoritative adjudication of a full game from its ordered moves. Replays via
 * `applyMove` (so every base rule still applies) AND ends the instant a position
 * repeats REPETITION_LIMIT times since the last capture — the anti-stall rule.
 * This is what the server and the on-chain ReplayVerifier use to decide the
 * canonical result; a losing player can no longer drag a dead position out to
 * the 40-ply backstop. Throws on an illegal move (like `applyMove`).
 *
 * The repetition window RESETS on every capture: a capture removes seeds for
 * good, so a pre-capture position can never recur — only a truly stuck endgame
 * cycles, and it cycles fast (few seeds ⇒ few distinct positions).
 */
export function adjudicate(moves: number[], startTurn: 0 | 1 = 0): GameState {
  let s = initialState();
  s.turn = startTurn; // a match's first mover is fixed by the on-chain reveal
  const seen = new Map<string, number>();
  seen.set(positionKey(s), 1);
  for (const move of moves) {
    const before = s.store0 + s.store1;
    s = applyMove(s, move);
    if (s.over) return s; // a base rule already ended it (majority / starve / 40)
    if (s.store0 + s.store1 > before) {
      seen.clear(); // capture = real progress; no repetition carries across it
      seen.set(positionKey(s), 1);
      continue;
    }
    const key = positionKey(s);
    const count = (seen.get(key) ?? 0) + 1;
    seen.set(key, count);
    if (count >= REPETITION_LIMIT) return endByCycle(s);
  }
  return s;
}

/** True iff appending `move` to `moves` ends the game (by any rule, including
 *  repetition). Lets a live driver decide when to stop without re-deriving the
 *  whole adjudication itself. `moves` must be the accepted history so far. */
export function endsGame(moves: number[], move: number, startTurn: 0 | 1 = 0): boolean {
  return adjudicate([...moves, move], startTurn).over;
}

/** How many times the CURRENT position (the one reached after `moves`) has
 *  occurred SINCE THE LAST CAPTURE. 1 = first time seen. When it would reach
 *  REPETITION_LIMIT the game ends as a cycle — so a return of REPETITION_LIMIT-1
 *  means "one more repeat and the game is scored where it stands". Drives the
 *  live "repeating position" warning; 0 if the game is already over. */
export function repetitionCount(moves: number[], startTurn: 0 | 1 = 0): number {
  let s = initialState();
  s.turn = startTurn;
  if (s.over) return 0;
  const seen = new Map<string, number>();
  seen.set(positionKey(s), 1);
  let current = 1;
  for (const move of moves) {
    const before = s.store0 + s.store1;
    s = applyMove(s, move);
    if (s.over) return 0;
    if (s.store0 + s.store1 > before) {
      seen.clear();
      seen.set(positionKey(s), 1);
      current = 1;
      continue;
    }
    const key = positionKey(s);
    current = (seen.get(key) ?? 0) + 1;
    seen.set(key, current);
    if (current >= REPETITION_LIMIT) return 0; // this ply ends the game as a cycle
  }
  return current;
}

/** Why an `over` game ended, for a human-readable result line. `capture` is a
 *  normal finish with seeds still on the board (a majority ≥25, or a resign
 *  handled by the caller); `swept` means the board was emptied and split by
 *  side — the anti-stall outcome shared by starvation, repetition and the
 *  40-ply backstop. Null while the game is still going. */
export function endKind(s: GameState): "capture" | "swept" | null {
  if (!s.over) return null;
  const boardEmpty = s.pits.every((p) => p === 0);
  return boardEmpty ? "swept" : "capture";
}
