#!/usr/bin/env bash
# Generate the off-chain .env files from a Deploy broadcast.
#
# Run AFTER `forge script Deploy --broadcast`:
#   ./script/wire-env.sh [chainId] [rpcUrl]
# Defaults: chainId from the broadcast dir; rpcUrl inferred from the chain.
#
# Writes packages/game-server/.env and packages/app/.env.local with the deployed
# addresses. Secret keys (SERVER_SIGNER_KEY) are left as placeholders for you.

set -euo pipefail
cd "$(dirname "$0")/.." || exit 1
ROOT="$(cd .. && pwd)"

CHAIN_ID="${1:-}"
if [ -z "$CHAIN_ID" ]; then
  CHAIN_ID="$(ls broadcast/Deploy.s.sol 2>/dev/null | head -1)"
fi
[ -n "$CHAIN_ID" ] || { echo "no broadcast found — run forge script Deploy --broadcast first"; exit 1; }

BCAST="broadcast/Deploy.s.sol/$CHAIN_ID/run-latest.json"
[ -f "$BCAST" ] || { echo "missing $BCAST"; exit 1; }

case "$CHAIN_ID" in
  42220) DEF_RPC="https://forno.celo.org" ;;
  11142220) DEF_RPC="https://forno.celo-sepolia.celo-testnet.org" ;;
  *) DEF_RPC="http://127.0.0.1:8545" ;;
esac
RPC="${2:-$DEF_RPC}"

CHAIN_ID="$CHAIN_ID" RPC="$RPC" ROOT="$ROOT" BCAST="$BCAST" python3 - <<'PY'
import json, os

bcast = json.load(open(os.environ["BCAST"]))
chain_id = os.environ["CHAIN_ID"]; rpc = os.environ["RPC"]; root = os.environ["ROOT"]

addr = {}
mocks = []
for t in bcast["transactions"]:
    if t.get("transactionType") == "CREATE":
        name, a = t["contractName"], t["contractAddress"]
        if name == "MockERC20":
            mocks.append(a)
        else:
            addr[name] = a

# deploy block = the earliest block any tx landed in (so /stats doesn't scan from 0)
blocks = [int(r["blockNumber"], 16) for r in bcast.get("receipts", []) if r.get("blockNumber")]
from_block = min(blocks) if blocks else 0

escrow = addr["MatchEscrow"]; verifier = addr["ReplayVerifier"]
# mock order matches the deploy script: USDm(18), USDC(6), USDT(6)
usdm = mocks[0] if mocks else "0x..."
testnet = "true" if chain_id != "42220" else "false"

server_env = f"""# generated by wire-env.sh from the Deploy broadcast
RPC_URL={rpc}
CHAIN_ID={chain_id}
ESCROW_ADDRESS={escrow}
VERIFIER_ADDRESS={verifier}
SERVER_SIGNER_KEY=0x...    # fill in a funded server key
FEE_CURRENCY={usdm}
PORT=8080
"""

app_env = f"""# generated by wire-env.sh from the Deploy broadcast
STATS_RPC_URL={rpc}
ESCROW_ADDRESS={escrow}
ESCROW_FROM_BLOCK={from_block}
CELO_TESTNET={testnet}

NEXT_PUBLIC_CHAIN_ID={chain_id}
NEXT_PUBLIC_RPC_URL={rpc}
NEXT_PUBLIC_ESCROW_ADDRESS={escrow}
NEXT_PUBLIC_VERIFIER_ADDRESS={verifier}
NEXT_PUBLIC_SERVER_URL=http://localhost:8080
NEXT_PUBLIC_STAKE_TOKEN={usdm}
NEXT_PUBLIC_STAKE_DECIMALS=18
NEXT_PUBLIC_FEE_CURRENCY={usdm}
"""

open(os.path.join(root, "packages/game-server/.env"), "w").write(server_env)
open(os.path.join(root, "packages/app/.env.local"), "w").write(app_env)
print("wrote packages/game-server/.env")
print("wrote packages/app/.env.local")
print(f"  escrow   {escrow}")
print(f"  verifier {verifier}")
print(f"  tokens   {', '.join(mocks) if mocks else '(using external addresses)'}")
PY

echo
echo "Note: on real Celo, set NEXT_PUBLIC_FEE_CURRENCY / FEE_CURRENCY to the token's"
echo "feeCurrency *adapter* for USDC/USDT (USDm is its own feeCurrency)."
